name: pytorch-gpu
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2024.3.11=haa95532_0
  - clang=12.0.0=h44fa016_2
  - clang-12=12.0.0=default_hec06eb5_2
  - clangxx=12.0.0=default_hec06eb5_2
  - colorama=0.4.6=py38haa95532_0
  - compiler-rt=12.0.0=h59b6b97_2
  - compiler-rt_osx-64=12.0.0=hfb26b64_2
  - compiler-rt_win-64=12.0.0=h6d14046_2
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - gmpy2=2.1.2=py38h7f96b67_0
  - icc_rt=2022.1.0=h6049295_2
  - importlib_resources=6.1.0=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.2=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang-cpp=14.0.6=default_h120b48b_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - matplotlib-base=3.7.2=py38h4ed8f06_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpld3=0.5.9=py38haa95532_0
  - mpmath=1.3.0=py38haa95532_0
  - munkres=1.1.4=py_0
  - numpy-base=1.24.3=py38h8a87ada_1
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.13=h2bbff1b_2
  - pip=23.2.1=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - pooch=1.7.0=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.18=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - sentencepiece=0.1.99=py38h59b6b97_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zipp=3.8.0=py38haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
    - absl-py==1.0.0
    - accelerate==0.32.1
    - ailment==9.2.102
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - angr==9.2.102
    - appdirs==1.4.4
    - archinfo==9.2.102
    - asgiref==3.7.2
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - attrs==23.2.0
    - axial-positional-embedding==0.2.1
    - backports-strenum==1.3.1
    - backports-zoneinfo==0.2.1
    - basic-utils==1.6.0
    - bitarray==2.9.2
    - bitstring==4.2.2
    - cachetools==5.0.0
    - capstone==5.0.0.post1
    - cchardet==2.1.7
    - certifi==2021.10.8
    - cffi==1.16.0
    - chardet==5.2.0
    - charset-normalizer==2.0.12
    - clarabel==0.7.1
    - claripy==9.2.102
    - cle==9.2.102
    - click==8.1.7
    - colorlog==6.8.2
    - colt5-attention==0.10.20
    - contourpy==1.1.1
    - cppheaderparser==2.7.4
    - cvxpy==1.4.2
    - cycler==0.12.1
    - dacite==1.8.1
    - datasets==2.18.0
    - decorator==5.1.1
    - dill==0.3.8
    - django==4.2.8
    - docker==7.1.0
    - docker-pycreds==0.4.0
    - dpkt==1.9.8
    - easy-torch==1.3.2
    - easydict==1.9
    - ebcompiler==0.1.3
    - ecos==2.0.13
    - einops==0.7.0
    - et-xmlfile==1.1.0
    - etsformer-pytorch==0.1.1
    - faker==26.0.0
    - filelock==3.13.1
    - flatbuffers==24.3.25
    - fonttools==4.43.1
    - frozenlist==1.4.1
    - fsspec==2023.10.0
    - func-timeout==4.3.5
    - future==1.0.0
    - gast==0.4.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gluonts==0.13.3
    - google-auth==2.29.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.63.0
    - h5py==3.11.0
    - huggingface-hub==0.22.2
    - idna==3.3
    - image==1.5.33
    - importlib-metadata==4.11.3
    - imutils==0.5.4
    - itanium-demangler==1.1
    - jieba==0.42.1
    - joblib==1.3.2
    - kanren==0.2.3
    - keopscore==2.2.2
    - keras==2.13.1
    - keras-applications==1.0.8
    - keras-utils==1.0.13
    - kiwisolver==1.4.5
    - libclang==18.1.1
    - lightning-utilities==0.11.2
    - local-attention==1.9.0
    - lxml==5.2.2
    - markdown==3.3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.6.2
    - matplotx==0.3.10
    - mdurl==0.1.2
    - mulpyplexer==0.9
    - multidict==6.0.5
    - multipledispatch==1.0.0
    - multiprocess==0.70.16
    - mypy-extensions==1.0.0
    - mysql==0.0.3
    - mysqlclient==2.2.4
    - nampa==0.1.1
    - networkx==3.1
    - nomkl==0.0.3
    - numexpr==2.8.6
    - numpy==1.23.5
    - oauthlib==3.2.0
    - opencv-python==4.4.0.44
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - optim==0.1.0
    - orjson==3.10.0
    - osqp==0.6.5
    - packaging==23.2
    - pandas==1.5.1
    - pefile==2023.2.7
    - pillow==9.5.0
    - plumbum==1.8.3
    - ply==3.11
    - pocsuite==2.0.8
    - pocsuite3==2.0.8
    - prettytable==3.9.0
    - product-key-memory==0.2.10
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyarrow==15.0.2
    - pyarrow-hotfix==0.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.12.0
    - pycparser==2.22
    - pycryptodomex==3.20.0
    - pydantic==1.10.15
    - pydot==2.0.0
    - pyecharts==2.0.4
    - pyelftools==0.31
    - pyformlang==1.0.10
    - pygments==2.18.0
    - pykeops==2.2.2
    - pymysql==1.1.0
    - pyparsing==3.1.1
    - pyqt5==5.15.9
    - pyqt5-plugins==5.15.9.2.3
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.13.0
    - pyqt5-tools==5.15.9.3.3
    - pyre-extensions==0.0.29
    - pysmt==0.9.5
    - python-dotenv==1.0.1
    - pytorch-lightning==2.0.4
    - pytorch-warmup==0.1.1
    - pytz==2023.3.post1
    - pyvex==9.2.102
    - pywin32==306
    - pyyaml==6.0.1
    - qbstyles==0.1.4
    - qdarkstyle==3.2.3
    - qdldl==0.1.7.post1
    - qt-material==2.14
    - qt5-applications==5.15.2.2.3
    - qt5-tools==5.15.2.1.3
    - qtpy==2.4.1
    - reformer-pytorch==1.4.4
    - regex==2024.4.16
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - rich==13.7.1
    - rpyc==6.0.0
    - rsa==4.8
    - safetensors==0.4.3
    - scapy==2.5.0
    - scienceplots==2.1.1
    - scikit-learn==1.1.3
    - scipy==1.10.1
    - scs==3.2.4.post1
    - seaborn==0.13.0
    - sentry-sdk==1.44.1
    - setproctitle==1.2.3
    - setuptools==59.5.0
    - simplejson==3.19.2
    - smmap==5.0.1
    - sortedcontainers==2.4.0
    - sqlparse==0.4.4
    - sympy==1.11.1
    - tables==3.7.0
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.13.0
    - tensorflow-estimator==2.13.0
    - tensorflow-intel==2.13.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.4.0
    - threadpoolctl==3.2.0
    - timm==0.6.11
    - tokenizers==0.19.1
    - toolz==0.12.1
    - torch==2.0.0+cu118
    - torchaudio==2.0.1+cu118
    - torchmetrics==1.3.2
    - torchvision==0.15.1+cu118
    - tqdm==4.64.0
    - transformers==4.40.1
    - typing-extensions==4.2.0
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - unicorn==2.0.1.post1
    - unification==0.2.2
    - unique-log-filter==0.1.0
    - urllib3==1.26.18
    - utils==1.0.2
    - wandb==0.16.6
    - wcwidth==0.2.8
    - werkzeug==2.1.2
    - wrapt==1.16.0
    - xformers==0.0.19
    - xxhash==3.4.1
    - yarl==1.9.4
    - z3-solver==4.10.2.0
prefix: D:\Anaconda3\envs\pytorch-gpu
